# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [6]:
# Import torch
import torch

# Create random tensor
torch.tensor(torch.rand(5))

C:\Users\owner\AppData\Local\Temp\ipykernel_5732\1657549833.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(torch.rand(5))


tensor([0.4388, 0.5544, 0.2265, 0.6605, 0.0612])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [10]:
# Create another random tensor
a = torch.tensor(torch.rand(1,7))
b = torch.tensor(torch.rand(1,7))
# Perform matrix multiplication 

c = a @ b.T
c

C:\Users\owner\AppData\Local\Temp\ipykernel_5732\4063976540.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  a = torch.tensor(torch.rand(1,7))
C:\Users\owner\AppData\Local\Temp\ipykernel_5732\4063976540.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  b = torch.tensor(torch.rand(1,7))


tensor([[1.9899]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [12]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
a = torch.tensor(torch.rand(1,7))
b = torch.tensor(torch.rand(1,7))

# Matrix multiply tensors
c = a @ b.T
c



C:\Users\owner\AppData\Local\Temp\ipykernel_5732\2045238714.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  a = torch.tensor(torch.rand(1,7))
C:\Users\owner\AppData\Local\Temp\ipykernel_5732\2045238714.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  b = torch.tensor(torch.rand(1,7))


tensor([[1.1173]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(0)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [18]:
# Set random seed
torch.cuda.manual_seed(0)

# Check for access to GPU
if torch.cuda.is_available():
    print("✅ GPU is available")
    print("Device name:", torch.cuda.get_device_name(0))
else:
    print("💕 GPU not available, using CPU")
# Create two random tensors on GPU

tensor_A = torch.tensor(torch.rand(2,2))
tensor_B = torch.tensor(torch.rand(2,2))
print(tensor_A)
print(tensor_B)

💕 GPU not available, using CPU
tensor([[0.1610, 0.2823],
        [0.6816, 0.9152]])
tensor([[0.3971, 0.8742],
        [0.4194, 0.5529]])


C:\Users\owner\AppData\Local\Temp\ipykernel_5732\1051249644.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor_A = torch.tensor(torch.rand(2,2))
C:\Users\owner\AppData\Local\Temp\ipykernel_5732\1051249644.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor_B = torch.tensor(torch.rand(2,2))



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [22]:
# Perform matmul on tensor_A and tensor_B
C = tensor_A.matmul(tensor_B)
print(C)

tensor([[0.1823, 0.2968],
        [0.6545, 1.1018]])


### 8. Find the maximum and minimum values of the output of 7.

In [23]:
# Find max
C.max()
# Find min
C.min()

tensor(0.1823)

### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
C.argmax()

# Find arg min
C.argmin()

tensor(0)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor
tensor_A = torch.tensor(torch.rand(1,1,1,10))
print(tensor_A)
# Remove single dimensions
tensor_A_ = tensor_A.squeeze()
print(tensor_A_)
# Print out tensors and their shapes

tensor([[[[0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038, 0.6511,
           0.7745, 0.4369]]]])
tensor([0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038, 0.6511, 0.7745,
        0.4369])


C:\Users\owner\AppData\Local\Temp\ipykernel_5732\2823107799.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor_A = torch.tensor(torch.rand(1,1,1,10))


In [ ]:
x = torch.tensor([1, 2, 3], dtype=torch.float32)
print(x.mean())         # tensor(2.)
print(x.mean().shape)   # torch.Size([]) → scalar
print(x.mean(0).shape)  # torch.Size([1]) → extra dimension

tensor(2.)
torch.Size([])
torch.Size([3])


In [37]:
x = torch.tensor([[1, 2, 3]], dtype=torch.float32)
print(x.mean())         # tensor(2.)
print(x.mean().shape)   # torch.Size([]) → scalar
print(x.mean(0).shape)  # torch.Size([1]) → extra dimension

tensor(2.)
torch.Size([])
torch.Size([3])


In [38]:
x.shape

torch.Size([1, 3])